### ISSUE TITLE
居然没人来，我先来填填这个坑把，我不是来玩的。

### ISSUE THREAD

**Issue by Abo233** [Jackiecrazy/Taoism#1]
楼主，你做mod的方向不对，有木有想过，你可以从生物上入手，因为目前主流是1.12.2，
  首先，您做的mod缺少联动性，武器装备啥的跟别的主流大模组匠魂啊。神秘显得格格不入，
装了也没什么用，别人会显太鸡肋。。至于HUD应该从原版的HUD下手，不是自己加入。。因为联动性太差，楼主可以考虑以饥饿度作为能量来实现对别的mod的兼容，武器加个升级系统，应该会比较火，可以进化。分成好几个形态。模型做的精致点，武器类型：戟，刀，枪，棍棒。剑
建议不要加武器的制作方法，改成地牢获取，或者您有能力的话，制作几个或一个boss，通过打败他获取武器基础形态，来使玩家获取武器。可以考虑加个本命武器的特殊设定。本命武器：武器自动护主，武器有生命形态（类似修仙里面的器灵，反正不用武器的时候，可以让他变成小跟班）
当到达一定形态解锁特性，比如走路的时候，有一圈火环环绕。玩家定期速度提升，自动照明啥的,定期给主人回血，定期抗性提升，什么小跟班根据属性发出远程攻击（频率要低），每当武器升级时降低攻击对玩家的饥饿损耗
  
我可能没提到生物类，楼主可以考虑一下重做一下御灵mod里的生物，尽量加山海经里面的水下怪物及生物，因为吧，我玩了好久的1.12.2，发现很多mod的生物都偏陆地，很少海洋类生物，醉了，我提意见貌似没几个人采纳。。。给怪物加个血量设定，攻击力设定，来实现对多个mod的兼容

**Comment by Abo233** [comment]
对了，本命武器只对本mod的武器起作用。来吸引玩家使用本mod。。楼主渲染方面做的比较好，可惜联动性太差。。

**Comment by Abo233** [comment]
属性方面就那几种，金木水火土

**Comment by Jackiecrazy** [comment]
我不想吗？
![image](https://user-images.githubusercontent.com/6895485/63637306-0f5d1880-c630-11e9-8399-021511c8bca6.png)
我的1.12.2的repository完全坏掉了！比起修理一个很快要被迭代的版本，我还是铤而走险上1.14吧……但是代码改了好多！tm把EntityLivingBase改成了LivingEntity！够我修改半天的了……然后现在的武器炼制系统完全有问题，武器升级我也同意，但是这样的话我的框架也得重写，又要几个星期……
![image](https://user-images.githubusercontent.com/6895485/63637402-91e5d800-c630-11e9-8f34-0860271e75f3.png)

**Comment by Abo233** [comment]
楼主，建议您先别更新mod到1.14

**Comment by Abo233** [comment]
在跳出来更新您说的mod，嘿嘿
这样这个模组就会被人注意
建议先去做好mod要用的模型

**Comment by Abo233** [comment]
我还有个比较新颖以及奇葩的想法

**Comment by Abo233** [comment]
攻击方式发生改变，不再是一位的左键右键，而是通过类似手写的方法，按左键蓄力控制剑的攻击轨迹，当划出一个类似图标的东西，便是触发技能，

**Comment by Abo233** [comment]
我看一个作者玩的魔法模组，就可以这样释放魔法

**Comment by Abo233** [comment]
说实在的，本命武器这个我觉得应该要有

**Comment by Abo233** [comment]
对了，楼主能帮帮忙吗？我想玩RTG,作者已经发了开发者版本的源码，我不会用，能不能您做成mod给我玩玩，我不传给别人，自己玩。。。我qq1492956011

**Comment by Jackiecrazy** [comment]
哦嚯，你看的是witchery。大型咒语可以这样触发，普通时候开这个对pvp来说太麻烦控制了。当前来讲，手握武器会召唤大型的武器虚影，和拔刀剑的渲染类似，以攻击有短暂的前摇为代价换来更远的攻击距离和极高的微操能力（aoe挥砍、单体竖劈、防御，根据武器会有一些变化）。攻击时会积攒气也就是连击条，到特定阈值可触发额外攻击效果（裂地斩、剑气、三连击），而灵气是独立的一个施法方式。

**Comment by Abo233** [comment]
楼主能不能构建个RTG的给我玩玩

**Comment by Abo233** [comment]
我好想加RTG到我的整合包里面

**Comment by Abo233** [comment]
我就一个人玩玩。。

**Comment by Jackiecrazy** [comment]
不行哦，我要上大学了，没时间啦

**Comment by Abo233** [comment]
构建要很长时间吗？

**Comment by Abo233** [comment]
楼主怎么构建的，教教我呗，至少大概告诉我，您大怎么构建的
