### ISSUE TITLE
Server crash with Toroquest ( i think)

### ISSUE THREAD

**Issue by Zack7292** [Jackiecrazy/Taoism#29]
so basically i'm in a modpack (Infinitely Exploring) and me and my friend are testing out for a server pack file, but we encounter a crash from your mod (server side). here is the crash log: https://pastebin.com/Pz2J02BM

**Comment by Jackiecrazy** [comment]
Toro is doing something bad, it just happens to be Taoism complaining because it intercepts the event first. I'll fix it on my side, but this one's on benchwench.
