### ISSUE TITLE
Random crash with Toro Quest Repoured

### ISSUE THREAD

**Issue by Zack7292** [Jackiecrazy/Taoism#30]
so basically when ur mod is with ToroQuest repoured you have a chance that your game crash crashlog: [crash-2020-07-13_20.02.40-server.txt](https://github.com/Jackiecrazy/Taoism/files/4915800/crash-2020-07-13_20.02.40-server.txt)

**Comment by Jackiecrazy** [comment]
This is fixed in the newest version of Toroquest.
