### ISSUE TITLE
[Improvement Suggestion] item registration improvements

### ISSUE THREAD

**Issue by Darkmega18** [Jackiecrazy/Taoism#31]
A Thought towards configuring items to work with parry and shielding.

Put the ability to manually balance items offensive and defensive power in the parry config so it become something like:

_modname:itemid,offensive#,defensive#

_dungeontactics:iron_cestus:1.5,0.8

which then makes the DT have those stats so one can for example make different tiers of same weapon stronger or weaker comparatively. if none are put, just fall back to the global number put in the config.

**Comment by Jackiecrazy** [comment]
done!

**Comment by Darkmega18** [comment]
👌
