### ISSUE TITLE
持有马槊的玩家引起的服务端崩溃：NullPointerException: Ticking player

### ISSUE THREAD

**Issue by RisingInIris2017** [Jackiecrazy/Taoism#36]
## Forge 版本
14.23.5.2854
## 御灵版本
taoism-2.2.1.22
## 单人游戏/多人游戏
多人游戏，使用服务端 [Mohist](https://github.com/Mohist-Community/Mohist)。
## 崩溃报告的链接
https://paste.ubuntu.com/p/VMFtT8bv3K/
https://paste.ubuntu.com/p/bffxwHP7Tn/
## 问题描述
这个持有马槊的玩家连续引起了几次服务端崩溃。崩溃报告的崩溃原因都是 Ticking player，
栈帧部分大致相同，故不一一列出，仅举出两例。
能够稳定复现此问题的手段尚不明确。
如果需要任何其他的信息，我会尽量提供。
在此事先感谢您的帮助！

**Comment by Jackiecrazy** [comment]
应该是修好了。
